dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=flake8

install:
  - pip install tox
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  - tox

notifications:
  email: false
